export default fontFamily = [
    {
        label:'Acme-Regular',
        value:'Acme-Regular'
    },
    {
        label:'AlfaSlabOne-Regular',
        value:'AlfaSlabOne-Regular'
    },
    {
        label:'AmaticSC-Bold',
        value:'AmaticSC-Bold'
    },
    {
        label:'Anton-Regular',
        value:'Anton-Regular'
    },
    
    {
        label:'Blaka-Regular',
        value:'Blaka-Regular'
    },
    {
        label:'BlakaHollow-Regular',
        value:'BlakaHollow-Regular'
    },
    {
        label:'Cookie-Regular',
        value:'Cookie-Regular'
    },
    {
        label:'Fascinate-Regular',
        value:'Fascinate-Regular'
    },
    {
        label:'FascinateInline-Regular',
        value:'FascinateInline-Regular'
    },
    {
        label:'FjallaOne-Regular',
        value:'FjallaOne-Regular'
    },
    {
        label:'GentiumPlus-BoldItalic',
        value:'GentiumPlus-BoldItalic'
    },
    {
        label:'GreatVibes-Regular',
        value:'GreatVibes-Regular'
    },
    {
        label:'Joan-Regular',
        value:'Joan-Regular'
    },
    {
        label:'KdamThmorPro-Regular',
        value:'KdamThmorPro-Regular'
    },
    {
        label:'Lobster-Regular',
        value:'Lobster-Regular'
    },
    {
        label:'Monofett-Regular',
        value:'Monofett-Regular'
    },
    {
        label:'NanumMyeongjo-ExtraBold',
        value:'NanumMyeongjo-ExtraBold'
    },
    {
        label:'Pacifico-Regular',
        value:'Pacifico-Regular'
    },
    {
        label:'PatrickHand-Regular',
        value:'PatrickHand-Regular'
    },
    {
        label:'PermanentMarker-Regular',
        value:'PermanentMarker-Regular'
    },
    {
        label:'PressStart2P-Regular',
        value:'PressStart2P-Regular'
    },
    {
        label:'Rajdhani-Light',
        value:'Rajdhani-Light'
    },
    {
        label:'Roboto-Black',
        value:'Roboto-Black'
    },
    {
        label:'Sacramento-Regular',
        value:'Sacramento-Regular'
    },
    {
        label:'Satisfy-Regular',
        value:'Satisfy-Regular'
    },
    {
        label:'ShadowsIntoLight-Regular',
        value:'ShadowsIntoLight-Regular'
    },
    {
        label:'TiroGurmukhi-Italic',
        value:'TiroGurmukhi-Italic'
    },
    {
        label:'Yellowtail-Regular',
        value:'Yellowtail-Regular'
    },
]