export default fontFamily = [
    {
        label:'Acme-Regular',
        value:'Acme-Regular'
    },
    {
        label:'AlfaSlabOne-Regular',
        value:'AlfaSlabOne-Regular'
    },
    {
        label:'AmaticSC-Bold',
        value:'AmaticSC-Bold'
    },
    {
        label:'Anton-Regular',
        value:'Anton-Regular'
    },
    {
        label:'Assistant-VariableFont_wght',
        value:'Assistant-VariableFont_wght'
    },
    {
        label:'Blaka-Regular',
        value:'Blaka-Regular'
    },
    {
        label:'BlakaHollow-Regular',
        value:'BlakaHollow-Regular'
    },
    {
        label:'Caveat-VariableFont_wght',
        value:'Caveat-VariableFont_wght'
    },
    {
        label:'Changa-VariableFont_wght',
        value:'Changa-VariableFont_wght'
    },
    {
        label:'Cinzel-VariableFont_wght',
        value:'Cinzel-VariableFont_wght'
    },
]