export default {
  title: require('../assets/icons/title.png'),
  icon1: require('../assets/icons/icon1.png'),
  icon2: require('../assets/icons/icon2.png'),
  icon3: require('../assets/icons/icon3.png'),
  icon4: require('../assets/icons/icon4.png'),
  icon5: require('../assets/icons/icon5.png'),
  icon6: require('../assets/icons/icon6.png'),
  icon7: require('../assets/icons/icon7.png'),
  icon8: require('../assets/icons/icon8.png'),
  login: require('../assets/icons/icon_login.png'),
  close: require('../assets/icons/close.png'),
  editColor: require('../assets/icons/chromatic.png'),
  sortDow: require('../assets/icons/sortDow.png'),
  B: require('../assets/icons/B.png'),
  I: require('../assets/icons/I.png'),
  facebook: require('../assets/icons/facebook.png'),
  google: require('../assets/icons/google.png'),
  visibility: require('../assets/icons/visibility.png'),
  unvisibility: require('../assets/icons/unvisibility.png'),
  savefile: require('../assets/icons/savefile.png'),
};
